// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonarchAPI.Data;

namespace MonarchAPI.Migrations
{
    [DbContext(typeof(MonarchContext))]
    [Migration("20210630143842_AddUserMemberList")]
    partial class AddUserMemberList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonarchAPI.Models.CheckIn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingID")
                        .HasColumnType("int");

                    b.Property<string>("MeetingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MemberID");

                    b.HasIndex("UserID");

                    b.ToTable("CheckIn");
                });

            modelBuilder.Entity("MonarchAPI.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("MonarchAPI.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("MonarchAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MonarchAPI.Models.CheckIn", b =>
                {
                    b.HasOne("MonarchAPI.Models.Member", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonarchAPI.Models.User", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MonarchAPI.Models.Meeting", b =>
                {
                    b.HasOne("MonarchAPI.Models.User", null)
                        .WithMany("Meetings")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MonarchAPI.Models.Member", b =>
                {
                    b.HasOne("MonarchAPI.Models.User", null)
                        .WithMany("members")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MonarchAPI.Models.Member", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("MonarchAPI.Models.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Meetings");

                    b.Navigation("members");
                });
#pragma warning restore 612, 618
        }
    }
}
